image: alpine:edge

stages:
  - qa
  - test

lint:
  stage: qa
  before_script:
    - apk add --no-cache vala-lint
  script:
    - io.elementary.vala-lint

test:
  stage: test
  before_script:
    - apk add --no-cache vala gtk+3.0-dev libgee-dev sqlite-dev libhandy1-dev meson alpine-sdk git
  script:
    - meson build
    - meson test -v -C build

non-null:
  stage: test
  before_script:
    - apk add --no-cache vala gtk+3.0-dev libgee-dev sqlite-dev libhandy1-dev meson alpine-sdk git
  script:
    - env VALAC_FLAGS="--enable-experimental-non-null" meson build
    - meson test -v -C build
